"""Initial schema setup

Revision ID: 47cba171d38b
Revises: 
Create Date: 2026-05-11 00:19:42.024188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = '47cba171d38b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blender_objects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('description_embedding', Vector(dim=3072), nullable=True),
    sa.Column('asset_path', sa.String(), nullable=True),
    sa.Column('boundbox_x', sa.Float(), nullable=True),
    sa.Column('boundbox_y', sa.Float(), nullable=True),
    sa.Column('boundbox_z', sa.Float(), nullable=True),
    sa.Column('boundbox_offset_x', sa.Float(), nullable=True),
    sa.Column('boundbox_offset_y', sa.Float(), nullable=True),
    sa.Column('boundbox_offset_z', sa.Float(), nullable=True),
    sa.Column('radius', sa.Float(), nullable=True),
    sa.Column('radius_offset_x', sa.Float(), nullable=True),
    sa.Column('radius_offset_y', sa.Float(), nullable=True),
    sa.Column('radius_offset_z', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scenes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('brief_description', sa.String(length=255), nullable=True),
    sa.Column('brief_description_embedding', Vector(dim=3072), nullable=True),
    sa.Column('detailed_description', sa.Text(), nullable=True),
    sa.Column('detailed_description_embedding', Vector(dim=3072), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cameras',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scene_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('pos_x', sa.Float(), nullable=True),
    sa.Column('pos_y', sa.Float(), nullable=True),
    sa.Column('pos_z', sa.Float(), nullable=True),
    sa.Column('rot_x', sa.Float(), nullable=True),
    sa.Column('rot_y', sa.Float(), nullable=True),
    sa.Column('rot_z', sa.Float(), nullable=True),
    sa.Column('fov', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scene_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group_objects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scene_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('pos_x', sa.Float(), nullable=True),
    sa.Column('pos_y', sa.Float(), nullable=True),
    sa.Column('pos_z', sa.Float(), nullable=True),
    sa.Column('rot_x', sa.Float(), nullable=True),
    sa.Column('rot_y', sa.Float(), nullable=True),
    sa.Column('rot_z', sa.Float(), nullable=True),
    sa.Column('scale_x', sa.Float(), nullable=True),
    sa.Column('scale_y', sa.Float(), nullable=True),
    sa.Column('scale_z', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lights',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scene_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('pos_x', sa.Float(), nullable=True),
    sa.Column('pos_y', sa.Float(), nullable=True),
    sa.Column('pos_z', sa.Float(), nullable=True),
    sa.Column('rot_x', sa.Float(), nullable=True),
    sa.Column('rot_y', sa.Float(), nullable=True),
    sa.Column('rot_z', sa.Float(), nullable=True),
    sa.Column('scale_x', sa.Float(), nullable=True),
    sa.Column('scale_y', sa.Float(), nullable=True),
    sa.Column('scale_z', sa.Float(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('intensity', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_turns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('chat_id', sa.UUID(), nullable=True),
    sa.Column('user_prompt', sa.Text(), nullable=True),
    sa.Column('agent_response', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('renders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scene_id', sa.UUID(), nullable=True),
    sa.Column('camera_id', sa.UUID(), nullable=True),
    sa.Column('is_sketch', sa.Boolean(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('description_embedding', Vector(dim=3072), nullable=True),
    sa.Column('image_embedding', Vector(dim=3072), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scene_objects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scene_id', sa.UUID(), nullable=True),
    sa.Column('blender_object_id', sa.UUID(), nullable=True),
    sa.Column('group_object_id', sa.UUID(), nullable=True),
    sa.Column('pos_x', sa.Float(), nullable=True),
    sa.Column('pos_y', sa.Float(), nullable=True),
    sa.Column('pos_z', sa.Float(), nullable=True),
    sa.Column('rot_x', sa.Float(), nullable=True),
    sa.Column('rot_y', sa.Float(), nullable=True),
    sa.Column('rot_z', sa.Float(), nullable=True),
    sa.Column('scale_x', sa.Float(), nullable=True),
    sa.Column('scale_y', sa.Float(), nullable=True),
    sa.Column('scale_z', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['blender_object_id'], ['blender_objects.id'], ),
    sa.ForeignKeyConstraint(['group_object_id'], ['group_objects.id'], ),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('chat_turn_id', sa.UUID(), nullable=True),
    sa.Column('tool_call_id', sa.String(), nullable=True),
    sa.Column('tool_name', sa.String(), nullable=True),
    sa.Column('tool_input', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tool_output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chat_turn_id'], ['chat_turns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('array_modifiers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scene_object_id', sa.UUID(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('offset_type', sa.String(), nullable=True),
    sa.Column('factor_x', sa.Float(), nullable=True),
    sa.Column('factor_y', sa.Float(), nullable=True),
    sa.Column('factor_z', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['scene_object_id'], ['scene_objects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scene_object_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('array_modifiers')
    op.drop_table('agent_logs')
    op.drop_table('scene_objects')
    op.drop_table('renders')
    op.drop_table('chat_turns')
    op.drop_table('lights')
    op.drop_table('group_objects')
    op.drop_table('chats')
    op.drop_table('cameras')
    op.drop_table('scenes')
    op.drop_table('blender_objects')
    # ### end Alembic commands ###
