"""add_keywords_to_blender_objects

Revision ID: fa0fea151eff
Revises: 47cba171d38b
Create Date: 2026-05-11 23:08:59.275338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fa0fea151eff'
down_revision: Union[str, Sequence[str], None] = '47cba171d38b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1. Add the column as nullable first
    op.add_column('blender_objects', sa.Column('keywords', postgresql.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###

    # 2. Update all existing rows to have an array containing an empty string: [""]
    op.execute("UPDATE blender_objects SET keywords = ARRAY['']")
    
    # 3. Alter the column to be NOT NULL and set the default empty array for new rows
    op.alter_column('blender_objects', 'keywords', nullable=False, server_default='{}')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blender_objects', 'keywords')
    # ### end Alembic commands ###
